sweet_friends_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from sweet_friends_app import views
from django.urls import path, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
app_name = 'sweet_friends_app'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('logout/', views.user_logout, name='user_logout'),
    path('login/', views.user_login, name='user_login'),
    path('', views.home_page, name='home_page'),
    path('search/', views.search, name='search'),
    path('potential_friends/', views.potential_friends, name='potential_friends'),
    path('<int:user_id>', views.friend_detail, name='friend_detail'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('add_friend/<int:friend_id>/', views.add_friend, name='add_friend'),
    path('remove_friend/<int:friend_id>', views.remove_friend, name='remove_friend')]

sweet_friends_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sweet_friends_app.urls', namespace='sweet_fiends_app'))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sweet_friends_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.urls import reverse

class UserManager(BaseUserManager):
    def create_user(self, email, full_name, password, ):
        if not email:
            raise ValueError('Email is required!')
        if not full_name:
            raise ValueError('full name is required!')

        user = self.model(email=self.normalize_email(email), full_name=full_name)
        user.set_password(password)
        user.save(using=self.db)
        return user

class User(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')
    full_name = models.CharField(max_length=100, verbose_name='Полное имя')
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_manager = models.BooleanField(default=False)
    image = models.ImageField(upload_to='users')

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']
    search_fields =['full_name']
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def return_friends(self):
        friends = Friends.objects.filter(user_id=self.id)
        friends_id = []
        for friend in friends:
            friends_id.append(friend.friend_id)
        return friends_id

    def get_absolute_url(self):
        return reverse('sweet_friends_app:friend_detail', kwargs={'user_id': self.id})
    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Friends(models.Model):

    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    friend_id = models.CharField(max_length=50)
    is_hidden = models.BooleanField(default=False)
    status = models.BooleanField(default=False)
    class Meta:
        verbose_name = 'Друг'
        verbose_name_plural = 'Друзья'
    def return_friend_info(self,friends_id:list):
        info =[]
        for friend_id in friends_id:
            friend_info = User.objects.filter(id = friend_id)
            for friend in friend_info:
                for obj in friend:

                    info.append({'friend_info':obj})
        return info
    # def update(self):
    #     self.status= True
    #     return self.status
    def get_absolute_url(self):
        return reverse('sweet_friends:friend_detail', kwargs={'user_id': self.friend_id})

sweet_friends_app/forms.py
from django import forms
from .models import User
class UserRegistrationForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'почта'}
        )
    )
    full_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Введите имя целиком'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'пароль'}
        )
    )


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control', 'placeholder': 'почта'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'пароль'}
        )
    )

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['full_name', 'email','image']
        widgets = {'full_name': forms.TextInput(attrs={'placeholder':'Фамилия, имя, отечество'},),
                   'email': forms.EmailInput(attrs={'placeholder':'Пример: User@mail.ru'})}

sweet_friends_app/views.py
from django.contrib import messages
from django.http import request, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import authenticate, login, logout
from sweet_friends_app.forms import UserRegistrationForm, UserLoginForm, EditProfileForm
from sweet_friends_app.models import Friends, User

def paginat(request, list_objects:list):  # https://docs.djangoproject.com/en/5.0/topics/pagination/

    p = Paginator(list_objects, 2)
    page_number = request.GET.get('page')
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.page(1)
    except EmptyPage:
        page_obj = p.page(p.num_pages)
    return page_obj

def return_friends_list(user:User)->list:
    friends_id = User.return_friends(user) # v

    listus =[]
    for friend_id in friends_id:#v
        us = User.objects.filter(id=friend_id)
        for obj in us:
            listus.append(obj)
    return listus

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            user = authenticate(
                request, email=data['email'], password=data['password']
            )

            if user is not None:
                login(request, user)

                return redirect('sweet_friends_app:home_page')
            else:
                messages.error(
                    request, 'Имя или пароль неверны', 'danger'
                )
                return redirect('sweet_friends_app:user_login')
    else:
        form = UserLoginForm()
    context = {'title': 'Login', 'form': form}
    return render(request, 'login.html', context)


def home_page(request):
    print(type(request.user))
    if str(request.user) == 'AnonymousUser':
        return redirect('sweet_friends_app:user_login')
    else:
        user = User.objects.get(id=request.user.id)
        user_name = user.full_name
        return render(request, 'home.html', context={'user': paginat(request, return_friends_list(user)),
                                                     'user_name':user_name,
                                                     })

def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(
                data['email'], data['full_name'], data['password'],
            )
            login(request, user)
            return redirect('sweet_friends_app:home_page')

    else:
        form = UserRegistrationForm()
    context = {'title': 'Signup', 'form': form}
    return render(request, 'register.html', context)

def user_logout(request):
    logout(request)
    return redirect('sweet_friends_app:user_login')
@login_required
def potential_friends(request):
    user = request.user
    objects = User.objects.all()
    potencial_friends_list =[]
    for potential_friend in objects:
        if potential_friend != user and potential_friend not in User.return_friends(user):
            potencial_friends_list.append(potential_friend)


    context = {'potential_friends': potencial_friends_list}
    return render(request, 'potential_friends.html', context)


@login_required
def friend_detail(request, user_id:User):
    friend = get_object_or_404(User, id=user_id)
    is_friend = str(user_id) in request.user.return_friends()
    print(str(user_id) in request.user.return_friends())

    context = {
        'return_friends': is_friend,
        'user': friend,
        'full_name': friend.full_name,
        'friends': paginat(request, return_friends_list(friend)),

    }

    return render(request, 'friend_detail.html', context)

def edit_profile(request):

    form = EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Ваш профиль был изменен', 'success')
        return redirect('sweet_friends_app:edit_profile')
    else:
        form = EditProfileForm(instance=request.user)
    context = {'title':'Edit Profile', 'form':form}
    return render(request, 'edit_profile.html', context)

@login_required
def add_friend(request, friend_id:int):
    friend = User.objects.get(id=friend_id)
    if str(request.user.id) not in User.return_friends(friend): # если я не в его друзьях то:
        Friends.objects.create(user_id=request.user, friend_id=friend_id)
    else:
        recording = Friends.objects.get(friend_id= str(request.user.id), user_id=friend.id)
        recording.status = True
        recording.save()
        Friends.objects.create(user_id=request.user, friend_id=friend_id, status=True)

    return friend_detail(request, friend_id)


def remove_friend(request,friend_id:int):
    friend = Friends.objects.get(friend_id=friend_id)
    friend.delete()
    return friend_detail(request, friend_id)

def search(request):
    query = request.GET.get('q')
    searched_user = User.objects.filter(full_name__icontains=query).all()
    context = {'user':paginat(request,searched_user)}
    return render(request,'home.html', context)

sweet_friends_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% if title %} {{ title }} {% else %} Django Online Shop {% endif %}</title>
</head>
<body>
<header class="p-2 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <i class="material-icons h3" style="color: red;">&#xe87d;</i>
          <li><a  href="{% url 'sweet_friends_app:home_page' %}" class="nav-link px-2 text-dark">Сладкие друзья</a></li>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'sweet_friends_app:search' %}">
            <input name="q" type="search" class="form-control form-control-dark" placeholder="Поиск..." aria-label="Search">
            </form>
            <div class="dropdown text-end">
            <a href="#" class="btn btn-primary text-white me-4 d-block link-dark text-decoration-none dropdown-toggle"id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">Профиль</a>
            <ul class="dropdown-menu" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="{% url 'sweet_friends_app:potential_friends' %}">Посмотреть возможных друзей</a></li>
                <li><a class="dropdown-item text-danger" href="{% url 'sweet_friends_app:user_logout' %}">Выйти</a></li>

            </ul>
            </div>
        </ul>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</header>
<main class="container">
        <div class="row mt-3">
          <!-- messages -->
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
          {% endif %}
          <!-- content -->
          {% block content %}{% endblock %}
        </div>
      </main>
</body>
</html>

sweet_friends_app/templates/edit_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}

{% block content %}

    <div  class="col-md-6">

        <form method="POST">

            <h3>Настройки профиля</h3>
            <hr>
            {% csrf_token %}
            {% bootstrap_form form %}



            <div class="form-group">
                <button class="btn btn-primary mt-3 w-100" type="submit">Обновить информацию</button>

            </div>


        </form>

    </div>
{% endblock %}

sweet_friends_app/templates/friend_detail.html
{% extends 'base.html' %}
{% block content %}
</body>

<div class="card me-2 mb-2" style="width: 16rem;">
    <img style="object-fit: cover;" class="card-img mt-2" width="260" height="250" src="{{ user.image.url }}">
    <div class="mt-3 text-center">
      <a href="" class="mb-3 btn btn-outline-primary w-100">{{user.full_name}}</a>
        {% if return_friends == True %}
        <a href="{% url 'sweet_friends_app:remove_friend' user.id %}" class="btn btn-outline-danger mt-2 text-capitalize ">Удалить из сладких друзей </a>
        {% else %}
        <a href="{% url 'sweet_friends_app:add_friend' user.id %}" class="btn btn-outline-danger mt-1  ">Добавить в сладкие друзья </a>
        {% endif %}




    </div>
</div>


</body>
</html>
<div class="row mt-4 mb-4">
    <h3>Сладкие друзья {{user.full_name}}:</h3><hr>
    {% for p in friends %}

            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="218" height="150" src="{{ p.image.url }}">
                <div class="mt-3 text-center">

                <a href="{{p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">{{ p.full_name }}</a>
                </div>
            </div>

    {% endfor %}
</div>
{% endblock %}

sweet_friends_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
</body>

{% for user_info in user %}


  <div class="card me-2 mb-2" style="width: 16rem;">
    <img style="object-fit: cover;" class="card-img mt-2" width="260" height="250" src='{{user_info.image.url}}'>
    <div class="mt-3 text-center">
      <a href="{{ user_info.get_absolute_url}}" class="mb-3 btn btn-outline-primary w-100">{{user_info.full_name}}</a>
    </div>
  </div>



{% endfor %}
<center class="mt-5">
  <div class="col-md-2">
    <ul class="pagination">
      {% if user.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ user.previous_page_number }}">Previous</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ user.previous_page_number }}">{{user.previous_page_number}}</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link" href="?page={{ user.number }}">{{user.number}}</a></li>
      {% if user.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ user.next_page_number }}">{{user.next_page_number}}</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ user.next_page_number }}">Next</a></li>
      {% endif %}
    </ul>
  </div>
</center>


{% endblock %}
<!--  <div class="card me-2 mb-2" style="width: 16rem;">-->
<!--    <img style="object-fit: cover;" class="card-img mt-2" width="260" height="250" src='{{user_info.image}}'>-->
<!--    <div class="mt-3 text-center">-->
<!--      <a href="{{ user_info.get_absolute_url}}" class="mb-3 btn btn-outline-primary w-100">{{user_info.full_name}}</a>-->
<!--    </div>-->
<!--  </div>-->

sweet_friends_app/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}

            <h3>Войти в личный кабинет</h3>
            {{form}}

            <div class="form-group">

                <button class="btn btn-primary mt-3 w-100" type="submit">Войти</button>
            </div>
            <div class="mt-2 mb-2">
                <small class="">
                    <a class="text-decoration-none text-danger" </a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                 <a class="text-decoration-none" href="{% url 'sweet_friends_app:user_register' %}">Создать учетную запись</a>
            </small>
        </div>
    </div>
{% endblock %}
<!--href="{% url 'accounts:password_reset' %}">Забыли пароль?-->

sweet_friends_app/templates/potential_friends.html
{% extends "base.html" %}
{% block content %}

</body>

<div class="row mt-4 mb-4">
    <h3>Возможные "Сладкие друзья" :</h3><hr>
    {% for p in potential_friends %}
        <!-- dont show the current product in this page -->
        {% if p != user %}

            <div class="card me-2 mb-2" style="width: 16rem;">
                <img style="object-fit: cover;" class="card-img mt-2" width="218" height="150" src="{{ p.image.url }}">
                <div class="mt-3 text-center">

                <a href="{{p.get_absolute_url }}" class="mb-3 btn btn-outline-primary w-100">{{ p.full_name }}</a>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

sweet_friends_app/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <h3>Создать учетную запись</h3>
            <hr>
            {{ form }}
            <div class="form-group">
                <button class="btn btn-primary w-100 mt-2" type="submit">подтвердить</button>
            </div>
        </form>
        <div class="mt-3">
            <small class="text-muted">
                Уже зарегистрирован?<a href="{% url 'sweet_friends_app:user_login' %}"> Войти</a>
            </small>
        </div>
    </div>
{% endblock %}
<!--<a href="{% url 'sweet_friends:user_login' %}">Войти-->